### PR TITLE
Adding fizzbuzz code

### PR DESCRIPTION
**Pull request by Al1999**

### CODE REVIEW

**Comment by KSKRLIFE** [comment]
Your code looks perfect and I didn't find anything that can be improved.

**Comment by mahlpdx** [comment]
Looks good! The main things I'd point out is that some of the code could more closely follow the airbnb style guidelines. Namely, comparisons should use === instead of == ( https://github.com/airbnb/javascript#comparison-operators--equality) and using higher-order functions instead of for loops (https://github.com/airbnb/javascript#iterators-and-generators).

**Comment by JeremyIV** [comment]
> using higher-order functions instead of for loops

I think this is a perfectly reasonable place to use a for loop. The airbnb guidelines recommend against using `for ... in` and `for ... of` loops, but not your basic c-style for loop like is used here. I don't think there's a better functional alternative to a for loop for this.

**Review by JeremyIV — APPROVED** [review]
A couple of minor formatting nits: you are not consistent with whether the opening curly brace `{` goes on a new line or not, nor whether loop/if statement conditions are padded with a space or not (`if ( foo )` vs. `if (foo)`). An autoformatter will make be consistent about all these little decisions. Otherwise, everything looks good.

**Comment by Al1999** [comment]
> Your code looks perfect and I didn't find anything that can be improved.

**Comment by SwaroopaSK** [comment]
Hi AI, Usage of variable name is nice and your code looks good.

**Pull request merged**
