### PR TITLE
New Code for assignment #2

### PR DESCRIPTION
**Pull request by Al1999**
Added new code for assignment #2 which includes 4 exercises ready to be reviewed :). Let me know your opinion and any ideas that might improve my work.

Thank you!

### CODE REVIEW

**Review by rohan-singh1 — APPROVED** [review]
My feedback for the questions:
1. I especially liked the way you split the decimal parts and the whole parts of the amount, I feel that makes the code simpler and easier to understand.
2. I didn't even consider that I could've used a reverse function; well played man!
3.  Good clean code.
4. I noticed that the code doesn't display the country names in an alphabetically sorted list; you might want to look into that.

Good job man!

**Comment by KSKRLIFE** [comment]
Hi Al,

Like Rohan mentioned sort is missing in the 4th one and I tried ( n/ 25...) In the coins program and it didn't work as expected
so I used Math.Trunc(n/25..) Looks like you accomplished it without math.trunc.

Good work. Thank you.

**Comment by JeremyIV** [comment]
Your solution to the coins question has a syntax error on line 15 and a runtime error on line 17. Please double-check that your code is all in working order before closing the PR. A smaller nit is that you're not consistent about pluralization: "dime" is always singular, the rest of the coin names are always plural, no matter the number of each coin. I would also recommend converting the number of pennies to an integer immediately, to avoid floating point rounding errors while you calculate the change.

For exercise 3, it's generally better to get the entire form and then extract the inputs from that than it is to get each input element individually. E.g. `let form = document.querySelector('form');`, and then `form.elements.email.value`.

For exercise 4, the population numbers are not properly formatted with commas, as per the screenshot. This can be accomplished with `Number(x).toLocaleString()`.

Otherwise, everything looks good, nice job.

**Comment by JeremyIV** [comment]
Your solution to exercise 1 prints out decimal amounts of coins, e.g. 2.48 quarters, 1.2 dimes, 0.4 nickels. This is clearly not the correct behavior.

Ex2: After entering an 8-digit and a non-8-digit number, both the error message and success message appear simultaneously, which is somewhat confusing behavior.

EX3 has an accessibility issue: the feedback input is not properly associated with its label. You can catch these kinds of issues with an accessibility extension like Wave. The name and email fields should be marked as required, so that the form complains if you try to submit without filling them out. The reset button should be of type 'reset', not 'submit'. Regarding the javascript, it's generally better to get the entire form and then extract the inputs from that than it is to get each input element individually. E.g. let form = document.querySelector('form');, and then form.elements.email.value. The logic to check of someone has clicked 'sign up for the newsletter' does not work, please test your code before submitting.

For the API exercise, it would be better to display something on the webpage and not just in the console if the api request fails.

**Pull request merged**
