### PR TITLE
Adding the solutions for hw3 exercises

### PR DESCRIPTION
**Pull request by Al1999**
Please review my code for homework #3. Thank you

### CODE REVIEW

**Comment by mahlpdx** [comment]
Hey Al,

On exercise 1, you set the content-type for all responses as 'text/html'. /cache, /cookie, and /check-cookies should respond with plain text. However, the written outputs for each url looks good. 

On exercise 2, the code could be a little bit more concise. For example, you have call res.write 4 times your .forEach() loops, but could consolidate all of this into a single formatted string. I think this modification could improve code readability. 

On exercise 3, I like your Form function -- it makes debugging simpler. Each of your routing conditionals are straightforward and easy to read.

Good job!

**Comment by TimmyYoung** [comment]
Exercise #1 looks correct minus the few suggestions made by mahl! Not a ton of room for creativity in this exercise. Code formatting looks clean and easy to read!! 

Exercise #2 could look a little bit cleaner, but reaches the desired solution. Formatting and code style are adequate, but some function calls could be written into simpler/smaller lines of code. 

Exercise #3 has quite a bit more code than my solution and some others I have seen. I do however like how you can see the formatting for your html tables/pages easily! It is easy to see your formatting decisions and where your information is pulling from/going too. It is a large amount of code but overall it was done well and with some considerable care it seems. 

Nice work and thanks for giving me a chance to review!

**Review by TimmyYoung — APPROVED** [review]
Exercise https://github.com/Al1999/fullstack-homework/pull/1 looks correct minus the few suggestions made by mahl! Not a ton of room for creativity in this exercise. Code formatting looks clean and easy to read!!

Exercise https://github.com/Al1999/fullstack-homework/pull/2 could look a little bit cleaner, but reaches the desired solution. Formatting and code style are adequate, but some function calls could be written into simpler/smaller lines of code.

Exercise https://github.com/Al1999/fullstack-homework/pull/3 has quite a bit more code than my solution and some others I have seen. I do however like how you can see the formatting for your html tables/pages easily! It is easy to see your formatting decisions and where your information is pulling from/going too. It is a large amount of code but overall it was done well and with some considerable care it seems.

Nice work and thanks for giving me a chance to review!

**Comment by SwaroopaSK** [comment]
Your code looks neat but could have minimized the code in exercise 2. Exercise 3 is easy to understand and nice usage of functions. Great job!

**Pull request merged**
